### ISSUE TITLE
gitlab ci set-up

### ISSUE THREAD

**Issue by kewgrz** [stsvilik/wdio-docker-service#106]
Really appreciate this service!

I'm pretty new to setting up CI. I'm trying to set this up in gitlab. This perhaps is not much of an issue or maybe not the right place to ask this so I apologize if so. I'm having an issue with connecting to the port and I'm not sure how to solve this issue. Is there perhaps an example or something that could point me in the right direction?

'ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444'
'ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/wd/hub", make sure browser driver is running on that address.'

I've set-up my wdio.config in this manner according to the example. This is my custom one:

`const { config } = require('./shared.wdio.conf')

config.services = ['docker'],
config.hostname = 'localhost',
config.port = 4444,
// config.path = '/',
config.path = '/wd/hub', // Required to work with wdio v6

config.dockerOptions = {
  image: 'selenium/standalone-chrome',
  healthCheck: 'http://localhost:4444',
  maxRetries: 3,
  inspectInterval: 1000,
  startDelay: 2000,
  options: {
      p: ['4444:4444'],
      shmSize: '2g',
  }
}`

docker-compose.yml:

version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    restart: always
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    scale: 2
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    restart: on-failure:3
  chrome:
      image: selenium/node-chrome-debug:latest
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - selenium-hub
      scale: 2
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
      restart: on-failure:3  
`
the gitlab-ci :

`image: tmaier/docker-compose:latest
services:
  - docker:dind

before_script:
  - docker info
  - docker-compose build
  - apk add nodejs npm && npm run build

stages:
  - chrome
chrome:
  stage: chrome
  script:
    - docker-compose up -d
    - docker ps
    - docker=true npm run blah:spec login
  artifacts:
   when: always
   expire_in: 1 day
   paths:
    - errorShots/
    - reports/
`

**Comment by stsvilik** [comment]
@kewgrz if you have solved your problem, do you mind sharing what it was?
