### ISSUE TITLE
Limitations of this service?

### ISSUE THREAD

**Issue by ShootingKing-AM** [stsvilik/wdio-docker-service#122]
Can I, with the help of this service, connect to Electron app (Chrome based) which is running in a docker Container run by this service ? What should the baseUrl be in that case ?

**Comment by stsvilik** [comment]
@ShootingKing-AM as with any app which runs in docker, it would primarily bind to localhost. With that said, if your app is containerized and you let service start it, then your base url would be `localhost` running on whatever port you expose.

**Comment by ShootingKing-AM** [comment]
Thanks !
