### ISSUE TITLE
_fsExtra2.default.readFile(...).then(...).finally is not a function

### ISSUE THREAD

**Issue by rycornell** [stsvilik/wdio-docker-service#25]
When I run wdio, I get this error:

    A service failed in the 'onPrepare' hook
    TypeError: _fsExtra2.default.readFile(...).then(...).finally is not a function
        at Docker._removeStaleContainer C:\Repos\AppRiver.Shakedown\e2e\webdriverio\node_modules\wdio-docker-service\lib\utils\docker.js:212:19)

When I remove the `finally` block from the `_removeStaleContainer` method, it works fine.

My setup is:
wdio-docker-service: 1.1.7
webdriverio: 4.12.0
node: 8.10.0

**Comment by stsvilik** [comment]
Thank you @rycornell I'll take a look. This is likely due to `fsextra` Promise implementation which is not `bluebird` which I anticipated.

**Comment by stsvilik** [comment]
This should be fixed now. Please update your package.
