### ISSUE TITLE
[Feature Request] Extra dockerOptions to allow docker to start in longer period of time

### ISSUE THREAD

**Issue by mouyigang** [stsvilik/wdio-docker-service#27]
I have an use case that the docker container starts really slow and the health check timeout in 5 seconds.
Could you allow us to pass in max retry as part of dockerOptions?
If possible, the following options will be great:
Interval(INSPECT_DOCKER_INTERVAL)
Start period(before start checking docker's health)
Retries(MAX_INSPECT_ATTEMPTS)

Many thanks

**Comment by stsvilik** [comment]
I'll see what I can do. I also encourage trying to add it yourself as a PR :)

**Comment by stsvilik** [comment]
Please review https://github.com/stsvilik/wdio-docker-service/pull/28
