### ISSUE TITLE
onDockerReady is called even though healthCheck.url isn't reachable

### ISSUE THREAD

**Issue by emilbader** [stsvilik/wdio-docker-service#30]
### Description
I might have misunderstood the purpose of `healthCheck` and the `onDockerReady` callback method, but in my experience, `onDockerReady` method is called even though an app isn't reachable. 

### Code to reproduce
Let's say I have an app that runs on `http://localhost:8080`. 
A working `wdio.conf.js` config could look like this:

```js
{
(...)
dockerLogs: './build/logs',
  dockerOptions: {
    image: 'MY_APP',
    healthCheck: {
      url: 'http://localhost:8080',
      maxRetries: 3,
      inspectInterval: 1000,
    },
    options: {
      p: ['8080:8080'],
    },
  },
  onDockerReady() {
    console.log('MY_APP CONTAINER IS UP');
  },
(...)
}
```

Now, If I were to change the `p` option to e.g. `['3030:'3030'']`, I would expect the `onDockerReady` method to not be called because the app is not configured to respond on port 3030. But it would still get called and `MY_APP CONTAINER IS UP` would appear in the console log.

### System information
- Node version: 8.11.2
- Npm version: 5.7.1
- wdio-docker-service: 1.2.0

**Comment by stsvilik** [comment]
Thank you @emilbader for bringing it up. I'll investigate this issue later this week.

**Comment by stsvilik** [comment]
@emilbader I tried your example using one of the tests in this repository `test/integration/docker-app` and was unable to replicate this issue. This leads me to believe that it might be possible that some other app may still use port `8080` on your machine. To test this theory can you try one of theses:
1. Hit `http://localhost:8080` while you running test with ports set to `3030:'3030`, and see if it responds.
2. Change port in url of your healthCheck to `http://localhost:3030`, while still mapping `8080:8080`.

**Comment by stsvilik** [comment]
Please update to version 1.3.0 to get the fix
