### ISSUE TITLE
Run docker with wdio-docker-service

### ISSUE THREAD

**Issue by danielleballas** [stsvilik/wdio-docker-service#33]
Hi,

i'm trying to run the tests with docker but but without success.
What is the right command that I should run?

**Comment by stsvilik** [comment]
Hi @danielleballas, 
It would help to know what you have tried already. 

How about answer these questions:
1. Do you have `webdriverio` installed on your machine?
2. Do you have `Docker` installed on your machine?
3. Did `wdio-docker-service` install ok?

I guess I just want to get an idea of where to start answering your question :)

**Comment by danielleballas** [comment]
Yes, all of them are installed.
But now I want to run the docker, What command should I run?

**Comment by stsvilik** [comment]
@danielleballas, this service would invoke `Docker` on its own. Question for you; Is your main app running in `Docker` and you want to test against it, OR your app is running locally and you want to use `Docker` to run `Selenium + Chrome` to test against it? There is a big difference between the two.

**Comment by danielleballas** [comment]
My app is running locally and i want to use Docker to run Selenium + Chrome

**Comment by stsvilik** [comment]
Have you tried following [wiki](https://github.com/stsvilik/wdio-docker-service/wiki/Selenium-Docker:-Testing-local-applications) instructions?

**Comment by stsvilik** [comment]
@danielleballas please let me know if you still having trouble. There is no "right" command to run test, it is all configurable through wdio config files documented in the wiki. If you need to know how to run webdriver tests in general, then its described [here](http://webdriver.io/guide/testrunner/gettingstarted.html)
