### ISSUE TITLE
Cidfile - Escape of spaces

### ISSUE THREAD

**Issue by NicklasWallgren** [stsvilik/wdio-docker-service#35]
Launching docker image 'selenium/standalone-chrome'
docker run --cidfile /mnt/jenkins/workspace/Project (Dev)/client/selenium_standalone_chrome.cid --rm -p 4444:4444 --shm-size 2g selenium/standalone-chrome
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by stsvilik** [comment]
Did you try escaping manually?

**Comment by stsvilik** [comment]
nvm previous comment, I see whats going on, I'll take a look

**Comment by stsvilik** [comment]
This has been fixed in latest version
