### ISSUE TITLE
Example on how to use hub and nodes

### ISSUE THREAD

**Issue by nealio42** [stsvilik/wdio-docker-service#51]
Hi, thank you for your amazing work on wdio-docker-service. Is there a way to configure dockerOptions section of my wdio.conf.js to allow for a hub with nodes? e.g. Instead of using the a standalone image, I would like to use the hub with chrome and firefox. Thanks!

**Comment by stsvilik** [comment]
Hello @nealio42 its great that you find my service useful :). So the thing about Selenium Hub is that it requires multiple containers or machines to run. The simplest way to run Selenium Hub locally is by using `docker-compose` as described (here)[https://github.com/SeleniumHQ/docker-selenium]. Unfortunately `wdio-docker-service` can only run one image at a time. I will likely add `docker-compose` support later. 

Realistically you don't need my service to start up Selenium Hub (those usually maintained by dev-ops and are available for entire company), you could use it to start up your app and use Selenium Hub running elsewhere to test against. 

If your application is not Dockerized or a public site, you don't need my (or any other) service at all - just spin up Selenium Hub locally as referenced above, and point `host` in `wdio.conf.js` file to `localhost`. Then you could setup as many browser capabilities as you'd like as long as Hub has those browsers in its pool.

**Comment by nealio42** [comment]
excellent! thanks for the response. Have a great day!
