### ISSUE TITLE
Docker events fails on windows

### ISSUE THREAD

**Issue by Sureiya** [stsvilik/wdio-docker-service#56]
Currently this does not work with docker on windows.

> Error: Error executing sub-child: docker events --format {{json .}} --filter image=selenium/standalone-chrome-debug

The following change to dockerEvents.js fixes it.

```
const DEFAULT_OPTIONS = {
  format: '"{{json .}}"'
};
```

**Comment by stsvilik** [comment]
@Sureiya strangely enough it fails on macOS :/ So you have tested with above change and it worked? The reason I ask is that above error can also appear when older version of Docker is installed (the one that doesn't support events).

**Comment by Sureiya** [comment]
Yes I have, I'm running the latest version of docker-desktop in windows.
I'm guessing we may need some more platform independent method to run the
command, or It may be that an upstream bug needs to be filed with docker on
windows? I'm leaning more towards the former.

**Comment by stsvilik** [comment]
@Sureiya sorry for long delay - I'm in the middle of a house move, is there a way you could put together a PR for this fix?

**Comment by abhijit945** [comment]
Is there any workaround for this?

**Comment by serbanghita** [comment]
@Sureiya just to be sure, do you have Win 10 Pro? I need to know how to test this on a Windows VM

**Comment by Sureiya** [comment]
@serbanghita I am using Windows 10 Pro build 1903

**Comment by webOS101** [comment]
I'm seeing the same issue running on Ubuntu 16.04.4.  I had another installation that was working fine before on the same server but appears to not be working anymore.

Docker version 18.06.0-ce, build 0ffa825

**Comment by webOS101** [comment]
I'm embarrassed to say that I made a little mistake and didn't have privileges to run docker.  I must have been testing with running the docker image standalone before.  Still having some issues but I did resolve that one at least.

**Comment by stsvilik** [comment]
@webOS101 you almost made me think that Docker has fixed that inconsistency - guess not :)

**Comment by stsvilik** [comment]
@Sureiya and @webOS101  could you check the RC version on Windows to see if it fixes the problem?

**Comment by calltojohn** [comment]
i see this on mac (10.13.6) running docker 2.1.0.4 (39773).  engine 19.03.4.

**Comment by stsvilik** [comment]
That's with version 2.1.5.rc.0?
________________________________

**Comment by calltojohn** [comment]
yeah.  2.1.5-rc.0

**Comment by stsvilik** [comment]
Would it be too much to ask for any of you to test my PR locally https://github.com/stsvilik/wdio-docker-service/pull/64. I added a code to handle docker events command based on OS, but looks like it doesn't work. I'm not really setup now to test on Windows :(

**Comment by stsvilik** [comment]
@calltojohn  and @webOS101  I have tested latest RC 2.1.5-rc.1 on my Windows machine and it works fine - do you mind giving it another shot?

**Comment by webOS101** [comment]
I don't use Windows and my problem was unrelated, it was a configuration error on my part.

**Comment by stsvilik** [comment]
closing this issue for now

**Comment by nvega-ms** [comment]
Hello! I just tested the latest RC 2.1.5-rc.1 on Windows, and I got the error :(

**Comment by stsvilik** [comment]
@nvega-ms do you mind sharing the error log? I'm testing on Windows 10 Pro 64 bit

**Comment by WeresForce** [comment]
Hi, @stsvilik , I just ran into this issue as well, here is log:
2020-01-28T16:57:09.039Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "docker"
2020-01-28T16:57:09.240Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-01-28T16:57:09.243Z DEBUG wdio-docker-service: Docker command: docker run --cidfile C:\autoTests\WebdriverIo\selenium_standalone_chrome_debug.cid --rm -p 4446:4444 --shm-size 2g selenium/standalone-chrome-debug
2020-01-28T16:57:09.252Z WARN wdio-docker-service: Connecting dockerEventsListener: 15304
2020-01-28T16:57:09.259Z INFO wdio-docker-service: Cleaning up CID files
2020-01-28T16:57:14.342Z WARN wdio-docker-service: NOTE: Pulling image for the first time. Please be patient.
2020-01-28T16:57:14.353Z ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format "{{json .}}" --filter image=selenium/standalone-chrome-debug
    at DockerEventsListener._onMessage (C:\autoTests\WebdriverIo\node_modules\wdio-docker-service\lib\utils\dockerEventsListener.js:67:21)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2020-01-28T16:57:14.356Z WARN wdio-docker-service: Disconnecting dockerEventsListener: 15304
2020-01-28T16:57:19.865Z ERROR wdio-docker-service: Failed to run container: Command 'docker,pull,selenium/standalone-chrome-debug' exited with code 1


Can You, please suggest ho could it be fixed?

**Comment by stsvilik** [comment]
@WeresForce the issue with `Error: Error executing sub-child` was addressed in the latest release. Do you mind sharing the version of `wdio-docker-service` and Windows version? Also make sure Docker is running on your machine, if not this could also cause errors.

**Comment by WeresForce** [comment]
@stsvilik yes, You are absolutely right, my bad, I missed that Docker has stopped on my machine. Thank You for help

**Comment by kumaramit-bhabra** [comment]
@stsvilik i am still getting this issue.. below is the error log for your reference

2020-01-29T21:16:40.765Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-01-29T21:16:40.805Z WARN wdio-docker-service: Connecting dockerEventsListener: 44
2020-01-29T21:16:40.834Z INFO wdio-docker-service: Cleaning up CID files
2020-01-29T21:16:40.892Z WARN wdio-docker-service: NOTE: Pulling image for the first time. Please be patient.
2020-01-29T21:16:40.953Z INFO @wdio/local-runner: Start worker 0-0 with arg:
2020-01-29T21:16:41.343Z ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format {{json\ .}} --filter image=selenium/standalone-chrome
    at DockerEventsListener._onMessage (/usr/app/node_modules/wdio-docker-service/lib/utils/dockerEventsListener.js:67:21)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

in package.josn i have got this as dependency
"wdio-docker-service": "^2.2.1",

I am running it on windows.. Can you please advise what's going wrong..

**Comment by kumaramit-bhabra** [comment]
@stsvilik below is the config in wdio.conf.js for service as docker..

services: ['docker'],
     dockerLogs: './',
     dockerOptions: {
         image: 'selenium/standalone-chrome',
         healthCheck: 'http://localhost:4444',
         options: {
             p: ['4444:4444'],
             shmSize: '2g'
         }
     },

**Comment by stsvilik** [comment]
Do you mind sharing windows version? Also make sure Docker service is running.
________________________________

**Comment by kumaramit-bhabra** [comment]
@stsvilik Thanks for the prompt reply. I am using Windows 10 Pro.. I am using Docker toolbox for windows and it's up and running

**Comment by stsvilik** [comment]
@kumaramit-bhabra Docker service is installed on your machine and runs in the background. On Windows you should see a Docker icon in the toolbar. Dockerfile when its built and runs creates a VM with its own OS. Each running container can map ports of its internally running application on to the host machine. When you expose a port it becomes accessible on your `localhost`.  For example you have a Dockerfile with inherits `FROM node`. Inside that container you can run your express app on port `8080`. You can expose that internal port `8080` on to your localhost on any other port. For this you need to map ports with `docker run -it -d -p 8080:8080 [image-name]`. Once you see that you could hit `localhost:8080` on your machine and see your express app being served, THEN you can run tests against it with this service :)

**Comment by kumaramit-bhabra** [comment]
@stsvilik thanks a lot for your inputs.

I deleted my Docker desktop and re-installed it again but still i am not able to run my test cases in the container..

After re-installing i am still getting the same issue ..
ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format {{json\ .}} --filter image=selenium/standalone-chrome

Docker services are also up and running. Once you have some time can you please look into this..

**Comment by kumaramit-bhabra** [comment]
For reference the image is currently at docker hub amitbhabra/wdio_asos

**Comment by stsvilik** [comment]
@kumaramit-bhabra do you mind going to `node` and telling me what value you see for `process.platform`? Also in order for you to run tests against your container, you must expose ports. When you run you container locally, can you hit it on the port exposed?

**Comment by kumaramit-bhabra** [comment]
@stsvilik Below is the value printed on console 
Value of opsys is win32. 

When i checked the computer properties, it say it's 64 bit. I have tried by exposing the port 4444 but no luck..

**Comment by kumaramit-bhabra** [comment]
@stsvilik Below is the error log for your reference.. hope this might be useful

2020-01-31T13:46:00.326Z INFO @wdio/local-runner: Start worker 0-0 with arg:
2020-01-31T13:46:00.434Z ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format {{json\ .}} --filter image=selenium/standalone-chrome
    at DockerEventsListener._onMessage (/usr/app/node_modules/wdio-docker-service/lib/utils/dockerEventsListener.js:67:21)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at emit (internal/child_process.js:881:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
2020-01-31T13:46:00.444Z WARN wdio-docker-service: Disconnecting dockerEventsListener: 44
[0-0] 2020-01-31T13:46:01.619Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /tests/landingPageTest.js
[0-0] 2020-01-31T13:46:02.111Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-01-31T13:46:02.129Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2020-01-31T13:46:02.130Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-01-31T13:46:02.224Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
[0-0] 2020-01-31T13:46:02.224Z INFO webdriver: Retrying 1/3
2020-01-31T13:46:02.225Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
2020-01-31T13:46:02.225Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }

**Comment by stsvilik** [comment]
Help me understand what are you trying to test.  Is your image running your application or selenium?
If your image runs your own application, then you need to run selenium in addition to your app (example is provided in wiki). If your image contains selenium, then your app must be hosted elsewhere on the web or locally.

Port 4444 belongs to selenium which actually automates all the tests.
________________________________

**Comment by prathameshnyt** [comment]
Thanks @stsvilik. I know we are talking about Windows here. On my personal MAC everything works fine but I am getting same error:

`2020-02-04T14:38:11.092Z ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format {{json\ .}} --filter image=<image>` with latest release while running the same tests as part of CI/CD pipeline. We are using https://drone.io/ and deployed using drone-terraform.  Can you please suggest?

**Comment by stsvilik** [comment]
Upsetting part is that everything works on my Windows 10 at home :(. Would you be able to echo value of `process.plarform` in Node running on your CI?
________________________________

**Comment by prathameshnyt** [comment]
Hi @stsvilik , in case of my local MAC it's `darwin` and in case of CI it's `linux` . Please let me know in case you need any other information. Thanks for looking.

**Comment by stsvilik** [comment]
@prathameshnyt thank you for that! As I don't have all possible environments to test on this sort of information is really important. I believe that core of this issue is in that difference between how Docker on different OS's works. I did not know that linux was also a subject to this issue as the CI this package tests run on is also a Linux OS. I will look into running more tests under various systems.

**Comment by prathameshnyt** [comment]
Thank you so much @stsvilik for looking into it. 

Thanks, 
Prathamesh

**Comment by stsvilik** [comment]
@prathameshnyt apparently my refactoring of options serialization code few PR's ago also eliminated the need to format that docker events JSON option differently for different OS's (who knew).  With that said please give a shot to my latest version `2.3.0`. Hope this settles this issue once and for all (fingers crossed).

**Comment by VisuSubbaiyan** [comment]
https://github.com/stsvilik/wdio-docker-service/issues/63, Still its not working for me.

**Comment by prathameshnyt** [comment]
Thanks @stsvilik. Getting same error with `2.3.0 `version.

Thanks,
Prathamesh

**Comment by stsvilik** [comment]
I guess it's something else. Anyway for you to get a printout of the log file generated by service?
________________________________

**Comment by prathameshnyt** [comment]
I will check. Thanks.

**Comment by prathameshnyt** [comment]
I see the same error https://github.com/stsvilik/wdio-docker-service/issues/63#issuecomment-581997657 Thanks, Prathamesh

**Comment by prathameshnyt** [comment]
May, it's not waiting for Docker to come up and not retrying as well though we have         

```
healthCheck: {
            url: 'http://localhost:4444',
            maxRetries: 3,
            inspectInterval: 2000,
            startDelay: 5000
        },
```

I killed docker application and started again on my local machine MAC, but before it starts completely, If I run the test, I am seeing above error.

Thanks,
Prathamesh

**Comment by stsvilik** [comment]
This is likely the issue, since starting docker doesn't guarantee the start of the app.
________________________________

**Comment by prathameshnyt** [comment]
@stsvilik , can you please check if startDelay setting works for you? Thanks.

**Comment by stsvilik** [comment]
@prathameshnyt Yes it does. Here is how I set that
```js
healthCheck: {
       url: 'http://localhost:4444',
       startDelay: 15000
},
```

**Comment by stsvilik** [comment]
@prathameshnyt One thing to note that service will try to use native docker healthcheck event to start testing earlier. What this means is if Dockerfile has `HEALTHCHECK` set and it signals in success, tests will not wait for artificial delay. Same also applies if Docker healthcheck is set via command line.

**Comment by prathameshnyt** [comment]
Ok, thanks. Not sure, why it's not waiting in my case. I have tried now with `image: 'selenium/standalone-chrome-debug'` I don't see `HEALTHCHECK`. 

Thanks,
Prathamesh

**Comment by prathameshnyt** [comment]
I see health-check [adding-a-healthcheck-to-the-grid](https://github.com/SeleniumHQ/docker-selenium/blob/5b7626c705bda91d90af4a7f74bb57b1e4056612/README.md#adding-a-healthcheck-to-the-grid added to Base image) added to Base image [Dockerfile](https://github.com/SeleniumHQ/docker-selenium/blob/5b7626c705bda91d90af4a7f74bb57b1e4056612/Base/Dockerfile)
