### ISSUE TITLE
options don't work properly

### ISSUE THREAD

**Issue by sathio** [stsvilik/wdio-docker-service#66]
Hi, I have these options

        options: {
            e: ["NODE_ENV=development", "FOO=bar"],
            p: ['4444:4444'],
            shmSize: '2g',
            rm: true
        }

when running wdio they get translated like this: 

    [... ]--rm -e=NODE_ENV=development -e=FOO=bar -p=4444:4444 --shm-size=2g 

not sure if I'm doing something wrong, I'm sure i saw them working earlier. 

        "wdio-docker-service": "^2.1.5-rc.0"

**Comment by stsvilik** [comment]
This is a new way of serialization. Does this break anything?
________________________________

**Comment by sathio** [comment]
well, yes, i can't set a proxy, if docker receives -e=https_proxy=http://proxy.com:1234  it is not recognised

**Comment by stsvilik** [comment]
Different serialization should not break anything. Here is what I ran and it works fine:
```bash
$ docker run -it -e=https_proxy=http://proxy.com:1234 nginx /bin/bash
root@227011abb15b:/# printenv
HOSTNAME=227011abb15b
NJS_VERSION=1.15.8.0.2.7-1~stretch
NGINX_VERSION=1.15.8-1~stretch
PWD=/
HOME=/root
https_proxy=http://proxy.com:1234
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/printenv
root@227011abb15b:/#
```

**Comment by stsvilik** [comment]
@sathio could you try new RC (`2.1.5-rc.1`) I pushed out and let me know if that works?

**Comment by sathio** [comment]
hi, i was in a weird state of mind when I was debugging the parser,  after hours of wrong tests. I'm sorry it seems it's indeed fine. I was carried away by the weird `-e=FOO=bar` syntax. thanks for your work
