### ISSUE TITLE
Does this package support images stored in AWS ECR?

### ISSUE THREAD

**Issue by selimyan** [stsvilik/wdio-docker-service#72]
Hi, sorry this is not an issue but a question. I'm using wdio and would like to run my tests in containers. My image is stored in AWS Elastic Container Repository. Can I use that url in dockerOptions.image?

**Comment by stsvilik** [comment]
I believe as long as docker pull can resolve it, it should work. With that said, you may need to configure your docker service to also have access to your AWS repo.
________________________________

**Comment by stsvilik** [comment]
Does this help? https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html

**Comment by selimyan** [comment]
Yes, docker pull with URI works when authenticated, thanks!
