### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:4444

### ISSUE THREAD

**Issue by ariesranjan** [stsvilik/wdio-docker-service#80]
Hi,
I am getting ERROR: connect ECONNREFUSED 127.0.0.1:4444 while using the wdio-docker-service. Below is my Dockerfile:
`FROM ubuntu:latest

LABEL maintainer="Ankit Ranjan"

ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

RUN apt-get -qqy update
RUN apt-get -qqy install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN echo "deb http://archive.ubuntu.com/ubuntu xenial main universe\n" > /etc/apt/sources.list \
  && echo "deb http://archive.ubuntu.com/ubuntu xenial-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu xenial-security main universe\n" >> /etc/apt/sources.list
RUN apt-get -qqy update

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get -qqy --no-install-recommends install \
  nodejs \
  # firefox \
  # google-chrome-stable \
  openjdk-8-jre-headless \
  x11vnc \
  xvfb \
  xfonts-100dpi \
  xfonts-75dpi \
  xfonts-scalable \
  xfonts-cyrillic

RUN export DISPLAY=:99.0
RUN Xvfb :99 -shmem -screen 0 1366x768x16 &

WORKDIR /home/node
ADD . .
RUN chown node:node -R .
RUN chmod 777 -R .

# RUN google-chrome --version
# RUN firefox --version
RUN node --version
RUN npm --version

USER node
RUN npm install

ENTRYPOINT ["tail", "-f", "/dev/null"]`

Below is my docker-compose file:

`version: "2"

services:

  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - testing-lan

  seleniumappchrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - testing-lan

networks:
  testing-lan:
    driver: bridge`

And below is my wdio-conf.js file:

`exports.config = {

    services: ['docker'],
    specs: [
        'bdd-tests/features/featureFiles/*.feature'
    ],
    
    maxInstances: 2,
    capabilities: [{
        maxInstances: 1,
        //
        browserName: 'chrome'
    },
],
    dockerOptions: [{
        image: 'selenium/standalone-chrome-debug',
        healthCheck: {
        url: 'http://0.0.0.0:4444/wd/hub',
        inspectInterval: 1000,
        startDelay: 15000
        },
        options: {
        p: ['4444: 4444', '5900:5900'],
        shmSize: '2g'
        }
        },
],
   
    framework: 'cucumber',
    reporters: ['cucumber-json', 'spec'],

    reporterOptions: {
        outputDir: 'bdd-tests/output/jsonReport',
    },
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        require: ['./bdd-tests/features/step-definitions/*.js'],// <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        compiler: [],       // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: 'json', // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tags: [],           // <string[]> (expression) only execute the features or scenarios with tags matching the expression
        timeout: 20000,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
    }
}
`
And below is the error I am getting:
`[16:36:57] Using gulpfile ~/gulpfile.js
[16:36:57] Starting 'cucumber'...
[16:36:57] Starting 'prepareReportFolders'...
[16:36:57] Finished 'prepareReportFolders' after 5.99 ms
[16:36:57] Starting 'selenium'...
[16:36:57] Finished 'selenium' after 3.24 ms
[16:36:57] Starting 'wdio'...
[16:36:57]  COMMAND	POST 	 "/wd/hub/session"
[16:36:57]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":1,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.4","name":"webdriverio"}}}
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
    at new RuntimeError (/home/node/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/home/node/node_modules/webdriverio/build/lib/utils/RequestHandler.js:342:43)
    at self.callback (/home/node/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/node/node_modules/request/request.js:877:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

Wrote json report to [bdd-tests/output/jsonReport].
[16:36:58] 'wdio' errored after 906 ms
[16:36:58] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1
[16:36:58] Finished 'cucumber' after 922 ms`

Please help me to find if I am missing anything.

Thanks,
Ankit Ranjan

**Comment by stsvilik** [comment]
@ariesranjan If you're trying to run tests agains a containerized app, you still need a selenium to run a test with. Look at one of the examples in the wiki https://github.com/stsvilik/wdio-docker-service/wiki/Testing-dockerized-application

**Comment by stsvilik** [comment]
@ariesranjan It is hard to discern what is that you're trying to do. Before dumping so much code, please explain your objective and I'll try to help you out as much as I can. Closing this for now.
