### ISSUE TITLE
Unable to use command and args docker options because it's appended after container name

### ISSUE THREAD

**Issue by hieuxlu** [stsvilik/wdio-docker-service#85]
I'm trying to add `--network host` command/args option but was blocked by below exception ).
```
2020-07-21T04:28:46.783Z INFO wdio-docker-service: Launching docker image 'selenium/standalone-chrome'
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
```

The real exception was below
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"--network\": executable file not found in $PATH": unknown.
```

Docker command
```
DEBUG wdio-docker-service: Docker command: docker run --cidfile /path-to/selenium_standalone_chrome.cid --rm -p 4444:4444 -p 5900:5900 --shm-size 2g selenium/standalone-chrome --network host
```
Moving `--network host` to before `selenium/standalone-chrome` and the command works.

I don't know if there's a reason why command and args are pushed behind container name. I think container name should be pushed last. 

I can create a PR to fix this if it makes sense to you.

```
    const cmdChain = ['docker', 'run'].concat((0, _optionsSerializer.default)(this.options), [this.image]);

    if (this.command) {
      cmdChain.push(this.command);
    }

    if (this.args) {
      cmdChain.push(this.args);
    }
```

Background: I could not use `addHost` because our login server only accepts `localHost` and that will be changing everywhere from localhost to, say `dockerhost`. So `docker --network host` is the only feasible option.

**Comment by stsvilik** [comment]
@hieuxlu do you mind sharing the configuration code where you try to include `--network host` value?

**Comment by stsvilik** [comment]
@hieuxlu have you tried this?
```js
dockerOptions: {
    image: 'selenium/standalone-chrome',
    healthCheck: 'http://localhost:4444',
    options: {
        p: ['4444:4444'],
        shmSize: '2g',
        network: "[host]"
    }
}
```

**Comment by hieuxlu** [comment]
@stsvilik Ah now it makes more sense. I was using `command` and `args`. It turns out any property in `options` will be serialized before `name`, so this works as well. Will try again tmr. Thanks.

**Comment by hieuxlu** [comment]
@stsvilik It works, thank you very much. Although I think the example is missing `path: /wd/hub` option to work with `wdio` v6, or wdio will always try to launch Chrome on host machine instead of one in docker container. 

Here's my wdio config. If you prefer, I can add this as another recipe for local development.

```
  const dockerConfig: WebdriverIO.DockerConfig = {
    path: '/wd/hub',
    services: ['docker'],
    dockerOptions: {
      image: 'selenium/standalone-chrome',
      healthCheck: 'http://localhost:4444',
      options: {
        shmSize: '2g',
        network: 'host',
      },
    },
    logToStdout: true,
  };
```

**Comment by stsvilik** [comment]
@hieuxlu It makes sense to put together a Wiki page with WDIO 6 recipes/recommendations

**Comment by hieuxlu** [comment]
@hieuxlu I created this PR to bump wdio version to v6. #86 Could you have a look? 

I will also update the wiki page as well on how `path` is needed for `wdio` v6 and how Selenium v4 docker image is not using `selenium/node-chrome-debug` anymore but an alpha image as mentioned on their wiki https://github.com/SeleniumHQ/docker-selenium#debugging
